theme: jekyll-theme-minimal
include: [ 'README_de.md',  'README.md', 'README_ja.md', 'README_MiMi_de.md',  'README_MiMi.md', 'README_MiMi_ja.md', 'test/README.md', 'profiles/README.md', 'testhelp.md'  ]

